services:
  - type: web
    name: aptoscomply-backend
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APTOS_NODE_URL
        value: https://fullnode.mainnet.aptoslabs.com/v1
      - key: APTOS_FAUCET_URL
        value: https://faucet.testnet.aptoslabs.com
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: aptos_compliance
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ONDEMAND_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /api/health

